name: RealMurderMystery
version: '${project.version}'
main: joserodpt.realmurdermystery.plugin.RealMurderMysteryPlugin
api-version: '1.14'
authors: [JoseGamer_PT]
description: Murder Mystery minigame plugin
load: POSTWORLD